config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'clips#index'
  resources :clips, only: [:edit, :update, :destroy, :new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/clip.rb
class Clip < ApplicationRecord
    validates :video_filename, presence: true
    validates :clip_starttime, presence: true
    validates :clip_endtime, presence: true # 00:00:00
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/clips_controller.rb
class ClipsController < ApplicationController
    def index
        @clips = Clip.all
    end

    def new
        @clip = Clip.new
    end

    def create
        clip = Clip.new(update_params)
        clip.save

        redirect_to root_path
    end

    def edit
        @clip = Clip.find(params[:id])
    end

    def update
        clip = Clip.find(params[:id])
        clip.update(update_params)

        redirect_to root_path
    end

    def destroy
        Clip.destroy(params[:id])

        redirect_to root_path
    end

    private

    def update_params
        field_list = Clip.columns.map{|c| c.name.to_sym}
        field_list.shift
        params.require(:clip).permit(field_list)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clips_helper.rb
module ClipsHelper
end

app/views/clips/edit.html.erb
<%= form_with model: @clip, url: clip_path(@clip.id), method: :patch, local: true do |f| %>
    <p>
        <%= f.label :is_finished, 'Processing finished?' %>
        <%= f.check_box :is_finished %>
    </p>
    <p>
        <%= f.label :is_finished, 'Finished publishing?' %>
        <%= f.check_box :is_published %>
    </p>
    <hr/>


    <p>
        <%= f.label :video_filename, 'Video Filename' %>
        <%= f.text_field :video_filename %>
    </p>
    <p>
        <%= f.label :clip_starttime, 'Clip Start' %>
        <%= f.text_field :clip_starttime, placeholder: '00:00:00' %>
    </p>
    <p>
        <%= f.label :clip_endtime, 'Clip End' %>
        <%= f.text_field :clip_endtime, placeholder: '00:00:00' %>
    </p>
    <hr/>


    <p>
        <%= f.label :is_podcast, 'Do Podcast processing?' %>
        <%= f.check_box :is_podcast %>
    </p>
    <p>
        <%= f.label :podcast_pub_datetime, 'Podcast Publication Date' %>
        <%= f.datetime_local_field :podcast_pub_datetime %>
    </p>
    <p>
        <%= f.label :podcast_title, 'Podcast Title' %>
        <%= f.text_field :podcast_title %>
    </p>
    <p>
        <%= f.label :podcast_desc, 'Podcast Desc' %>
        <%= f.text_field :podcast_desc %>
    </p>
    <p>
        <%= f.label :podcast_teaser_filename, 'Podcast Teaser Filename' %>
        <%= f.text_field :podcast_teaser_filename %>
    </p>
    <p>
        <%= f.label :podcast_teaser_starttime, 'Teaser Start' %>
        <%= f.text_field :podcast_teaser_starttime, placeholder: '00:00:00' %>
    </p>
    <p>
        <%= f.label :podcast_teaser_endtime, 'Teaser End' %>
        <%= f.text_field :podcast_teaser_endtime, placeholder: '00:00:00' %>
    </p>
    <hr/>


    <p>
    <%= f.label :is_youtube, 'Do YouTube processing?' %>
    <%= f.check_box :is_youtube %>
    </p>
    <p>
    <%= f.label :youtube_pub_datetime, 'YouTube Publication Date' %>
    <%= f.datetime_local_field :youtube_pub_datetime %>
    </p>
    <p>
    <%= f.label :youtube_title, 'YouTube Title' %>
    <%= f.text_field :youtube_title %>
    </p>
    <p>
    <%= f.label :youtube_desc, 'YouTube Desc' %>
    <%= f.text_field :youtube_desc %>
    </p>
    <p>
    <%= f.label :youtube_thumbnail_text, 'YouTube Thumbnail Text' %>
    <%= f.text_field :youtube_thumbnail_text, maxlength: 65 %>
    </p>
    <hr/>

    <p>
    <%= f.submit %>
    </p>
<% end %>

app/views/clips/index.html.erb
<ul>
<% @clips.each do |clip| %>
    <li id="clip-<%= clip.id %>">
        <%= link_to(clip.video_filename, edit_clip_path(clip.id)) %>,
        start: <%= clip.clip_starttime %>,
        end: <%= clip.clip_endtime %>,
        youtube_pub_date: <%= clip.podcast_pub_datetime %>,
        podcast_pub_date: <%= clip.podcast_pub_datetime %>,
        <%= link_to('delete clip', clip_path(clip.id), method: :delete) %>,
    </li>
<% end %>
</ul>

app/views/clips/new.html.erb
<%= form_with model: @clip, url: clips_path, method: :post, local: true do |f| %>
    <p>
        <%= f.label :is_finished, 'Processing finished?' %>
        <%= f.check_box :is_finished %>
    </p>
    <p>
        <%= f.label :is_finished, 'Finished publishing?' %>
        <%= f.check_box :is_published %>
    </p>
    <hr/>


    <p>
        <%= f.label :video_filename, 'Video Filename' %>
        <%= f.text_field :video_filename %>
    </p>
    <p>
        <%= f.label :clip_starttime, 'Clip Start' %>
        <%= f.text_field :clip_starttime, placeholder: '00:00:00' %>
    </p>
    <p>
        <%= f.label :clip_endtime, 'Clip End' %>
        <%= f.text_field :clip_endtime, placeholder: '00:00:00' %>
    </p>
    <hr/>


    <p>
        <%= f.label :is_podcast, 'Do Podcast processing?' %>
        <%= f.check_box :is_podcast %>
    </p>
    <p>
        <%= f.label :podcast_pub_datetime, 'Podcast Publication Date' %>
        <%= f.datetime_local_field :podcast_pub_datetime %>
    </p>
    <p>
        <%= f.label :podcast_title, 'Podcast Title' %>
        <%= f.text_field :podcast_title %>
    </p>
    <p>
        <%= f.label :podcast_desc, 'Podcast Desc' %>
        <%= f.text_field :podcast_desc %>
    </p>
    <p>
        <%= f.label :podcast_teaser_filename, 'Podcast Teaser Filename' %>
        <%= f.text_field :podcast_teaser_filename %>
    </p>
    <p>
        <%= f.label :podcast_teaser_starttime, 'Teaser Start' %>
        <%= f.text_field :podcast_teaser_starttime, placeholder: '00:00:00' %>
    </p>
    <p>
        <%= f.label :podcast_teaser_endtime, 'Teaser End' %>
        <%= f.text_field :podcast_teaser_endtime, placeholder: '00:00:00' %>
    </p>
    <hr/>


    <p>
    <%= f.label :is_youtube, 'Do YouTube processing?' %>
    <%= f.check_box :is_youtube %>
    </p>
    <p>
    <%= f.label :youtube_pub_datetime, 'YouTube Publication Date' %>
    <%= f.datetime_local_field :youtube_pub_datetime %>
    </p>
    <p>
    <%= f.label :youtube_title, 'YouTube Title' %>
    <%= f.text_field :youtube_title %>
    </p>
    <p>
    <%= f.label :youtube_desc, 'YouTube Desc' %>
    <%= f.text_field :youtube_desc %>
    </p>
    <p>
    <%= f.label :youtube_thumbnail_text, 'YouTube Thumbnail Text' %>
    <%= f.text_field :youtube_thumbnail_text, maxlength: 65 %>
    </p>
    <hr/>

    <p>
    <%= f.submit %>
    </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Podshorts</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>